// Generated by https://pagedraw.io/pages/15320
import React, { Component } from "react";
import { Link } from "react-router-dom";
import './About.css';


class About extends React.Component { 
  render() {
    return (
      <div className="desktop_hd-desktop_hd-1">
          <div className="desktop_hd-0">
              <div className="desktop_hd-path-4">
                  <div className="desktop_hd-0-0-0">
                      <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1591156387266031-1543903557969-5A7E3C28-E473-4135-B893-AA0568E07693.png" className="desktop_hd-risefreed_2" /> 
                      <div className="desktop_hd-0-0-0-1">
                          <div className="desktop_hd-0-0-0-1-0">
                              <div className="desktop_hd-home-6">Home</div>
                          </div>
                      </div>
                      <div className="desktop_hd-0-0-0-2">
                          <div className="desktop_hd-0-0-0-2-0">
                              <div className="desktop_hd-contact_us-3">Contact Us</div>
                          </div>
                      </div>
                      <div className="desktop_hd-0-0-0-3">
                          <div className="desktop_hd-0-0-0-3-0">
                              <div className="desktop_hd-faqs-2">FAQs</div>
                          </div>
                      </div>
                      <div className="desktop_hd-0-0-0-4">
                          <div className="desktop_hd-0-0-0-4-0">
                              <div className="desktop_hd-forms-1">Forms</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="desktop_hd-1">
              <div className="desktop_hd-1-0">
                  <div className="desktop_hd-1-0-0">
                      <div className="desktop_hd-1-0-0-0">
                          <div className="desktop_hd-path-1" /> 
                          <div className="desktop_hd-girlfriends-2">
                              <div className="desktop_hd-1-0-0-0-1-0">
                                  <div className="desktop_hd-risefreed_was_create-1">
                                      <div>RiseFreed was created by two roommates with a passion for tech and gender equality.</div>
                                      <br/>
                                      <div>Our project was coded in the common room of our dorm room on multiple late</div>
                                      <div>nights.</div>
                                      <br/>
                                      <div>Our dream is to help women feel empowered and free.</div>
                                      <br/>
                                      <div>Contact us at cjchen@college.harvard.edu and adrianarotaru@college.harvard.edu.</div>
                                      <br/>
                                      <div>{"We’d love to hear from you."}</div>
                                  </div>
                              </div>
                          </div>
                          <div className="desktop_hd-path-17" /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="desktop_hd-2" /> 
      </div>
    );
  }
};
export default About;
